version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev_db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 80:80
    env_file:
      - backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app
