version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - .env
    volumes:
      - mysql_data:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # args:
      #   - NODE_ENV=production
    container_name: backend
    ports:
      - 5500:5500
    env_file:
      - backend/.env
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./backend:/usr/src/app
      - proctoring:/usr/src/app/proctoring
volumes:
  mongo_data:
  mysql_data:
  proctoring:
