version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    volumes:
      - mysql_data:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 80:80
    env_file:
      - backend/.env
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./backend:/usr/src/app
      - ./backend/logo:/usr/src/app/logo
      - ./backend/answers:/usr/src/app/answers
      - ./backend/proctoring:/usr/src/app/proctoring
volumes:
  mongo_data:
  mysql_data:
